# site_url: https://example.com/
docs_dir: docs

site_name: Tempered
site_description: A modern html templating library for python
site_author: Ben Brady
repo_name: Tempered
repo_url: https://github.com/Ben-Brady/tempered

theme:
  name: material
  locale: en
  features:
    - content.code.copy
  logo: favicon.ico

  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: blue grey
    accent: amber
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: blue grey
    accent: amber
    toggle:
      icon: material/lightbulb-outline
      name: Switch to light mode

nav:
- Introduction: readme.md
- Home: index.md
- Quickstart: quickstart.md
- Templating: templating.md
- Reference: reference/tempered.md
- Examples: examples.md

plugins:
  mkdocstrings:
    handlers:
      python:
        options:
          show_root_heading: true
          show_if_no_docstring: true
          inherited_members: true
          members_order: source
          separate_signature: true
          unwrap_annotated: true
          filters:
            - '!^_'
          merge_init_into_class: true
          docstring_section_style: spacy
          signature_crossrefs: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
